### ISSUE TITLE
Able to Add New Opportunity Without Text in Required Fields

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#1796]
Issue: I was able to add an opportunity without required field "Headline" and "Description".

Steps to reproduce:
1.  Navigate to new opportunity page
2.  Navigate to "Headline" field
3.  Place cursor in field, hit spacebar
4.  Navigate to Description field
5.  Place cursor in field, hit spacebar
6.  Click "Submit for review"
7.  Sign into administration >task

Results:  Task is displayed without title

Resolution: A space should not be allowed to be saved by itself without any additional text.

**Comment by bmcorum** [comment]
Need to make sure we trim ALL inputs at the client and the server.

**Comment by kbwagner** [comment]
@margaretdumas - I think this issue is resolved.  Can you double check and if so close this ticket?  Thanks!

**Comment by kbwagner** [comment]
5/17/18 - KWagner tested - still an issue.

**Comment by margaretdumas** [comment]
06/04/2018 - Mdumas - Retested - This is still an issue.  I can add spaces in required fields and save an opportunity.  
![bug 1796](https://user-images.githubusercontent.com/19936109/40920509-c4ba7b88-67da-11e8-8e8a-617f2b504b23.gif)

Desired skills
What you'll do
Related Keywords

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome and mobile Safari
ready for final review.

**Comment by tlorrison** [comment]
Approved
