### ISSUE TITLE
IN Fire Fox, create internship, select agency alignment incorrect

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3306]
During the create process the alingment for the two agencies is incorrect.  The icon is centered when it should be left justified. see image. found during testing of 3289.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/3d71d53d-a97a-48d3-94a4-1e29265b3889)

**Comment by Kibrahacha67** [comment]
6-11-19 LHammond this has been resolved. moving to review.

**Comment by kbwagner** [comment]
6/12/19 - KWagner - this issue has been resolved.

**Comment by kbwagner** [comment]
![image](https://user-images.githubusercontent.com/18709918/59352143-f9f17700-8ced-11e9-9757-dcd2f8361d8b.png)

This is still an issue in Firefox

**Comment by raywilliams** [comment]
@kbwagner, what version of Firefox are you using? The latest release is 67.0.2. Here's how it looks in TEST in Firefox for me (version 67):
![openopps-create-opp-firefox](https://user-images.githubusercontent.com/340340/59353111-3faf3f00-8cf0-11e9-9891-b31ad2b58910.png)

**Comment by kbwagner** [comment]
It does look correct in the latest version and per USAJOBS help center we support the current and previous version.  https://www.usajobs.gov/Help/faq/troubleshoot/

I will close this as the second version on my computer is older and does not need to be supported.
